# Generated by Django 5.2 on 2025-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_bracket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['pk', 'name', 'url']},
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
